apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: circle-calculator-ingress
  namespace: circle-calculator
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "passkey-sticky"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - kowan-uas.andrewaryo.com
    secretName: circle-calculator-tls
  rules:
  - host: kowan-uas.andrewaryo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: circle-calculator-service
            port:
              number: 80
